export const employees = [
  {
    id: 1,
    employeeName: "Amit Sharma",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Prepare Sales Report",
        taskDescription: "Compile and prepare the monthly sales report",
        taskPriority: "High",
        category: "Reporting",
        creationDate: "2026-01-05",
        status: "active",
      },
      {
        taskTitle: "Client Follow-up",
        taskDescription: "Follow up with pending client emails",
        taskPriority: "Low",
        category: "Communication",
        creationDate: "2026-01-07",
        status: "new",
      },
      {
        taskTitle: "Data Cleanup",
        taskDescription: "Clean outdated entries from CRM",
        taskPriority: "Low",
        category: "Maintenance",
        creationDate: "2026-01-03",
        status: "completed",
      },
    ],
  },

  {
    id: 2,
    employeeName: "Neha Verma",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Bug Fixing",
        taskDescription: "Fix UI bugs on dashboard",
        taskPriority: "High",
        category: "Development",
        creationDate: "2026-01-06",
        status: "new",
      },
      {
        taskTitle: "Code Review",
        taskDescription: "Review PRs from teammates",
        taskPriority: "Low",
        category: "Development",
        creationDate: "2026-01-04",
        status: "completed",
      },
      {
        taskTitle: "Optimize Queries",
        taskDescription: "Improve database query performance",
        taskPriority: "High",
        category: "Performance",
        creationDate: "2026-01-02",
        status: "failed",
      },
    ],
  },

  {
    id: 3,
    employeeName: "Rohit Mehta",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Design Landing Page",
        taskDescription: "Create UI design for new landing page",
        taskPriority: "High",
        category: "Design",
        creationDate: "2026-01-08",
        status: "new",
      },
      {
        taskTitle: "Update Brand Assets",
        taskDescription: "Refresh logo and color palette",
        taskPriority: "Low",
        category: "Design",
        creationDate: "2026-01-01",
        status: "completed",
      },
      {
        taskTitle: "Prototype Review",
        taskDescription: "Review Figma prototype with team",
        taskPriority: "Low",
        category: "Review",
        creationDate: "2026-01-05",
        status: "failed",
      },
    ],
  },

  {
    id: 4,
    employeeName: "Pooja Singh",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Write Test Cases",
        taskDescription: "Create unit test cases for auth module",
        taskPriority: "High",
        category: "Testing",
        creationDate: "2026-01-06",
        status: "active",
      },
      {
        taskTitle: "Regression Testing",
        taskDescription: "Run regression test suite",
        taskPriority: "Low",
        category: "Testing",
        creationDate: "2026-01-03",
        status: "completed",
      },
      {
        taskTitle: "Bug Reporting",
        taskDescription: "Document and report found issues",
        taskPriority: "Low",
        category: "Documentation",
        creationDate: "2026-01-04",
        status: "failed",
      },
    ],
  },

  {
    id: 5,
    employeeName: "Karan Patel",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Server Monitoring",
        taskDescription: "Monitor server health and logs",
        taskPriority: "High",
        category: "DevOps",
        creationDate: "2026-01-07",
        status: "new",
      },
      {
        taskTitle: "Backup Setup",
        taskDescription: "Configure daily database backups",
        taskPriority: "High",
        category: "DevOps",
        creationDate: "2026-01-02",
        status: "completed",
      },
      {
        taskTitle: "Deploy Patch",
        taskDescription: "Deploy security patch to production",
        taskPriority: "High",
        category: "Deployment",
        creationDate: "2026-01-01",
        status: "failed",
      },
    ],
  },
];

export const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
    // tasks: [
    //   {
    //     taskTitle: "Prepare Sales Report",
    //     taskDescription: "Compile and prepare the monthly sales report",
    //     taskPriority: "High",
    //     category: "Reporting",
    //     creationDate: "2026-01-05",
    //     active: true,
    //     new: false,
    //     completed: false,
    //     failed: false,
    //     assignedTo: "employee1@example.com",
    //   },
    //   {
    //     taskTitle: "Client Follow-up",
    //     taskDescription: "Follow up with pending client emails",
    //     taskPriority: "Low",
    //     category: "Communication",
    //     creationDate: "2026-01-07",
    //     active: true,
    //     new: true,
    //     completed: false,
    //     failed: false,
    //     assignedTo: "employee1@example.com",
    //   },
    //   {
    //     taskTitle: "Data Cleanup",
    //     taskDescription: "Clean outdated entries from CRM",
    //     taskPriority: "Low",
    //     category: "Maintenance",
    //     creationDate: "2026-01-03",
    //     active: false,
    //     new: false,
    //     completed: true,
    //     failed: false,
    //     assignedTo: "employee1@example.com",
    //   },
    //   {
    //     taskTitle: "Bug Fixing",
    //     taskDescription: "Fix UI bugs on dashboard",
    //     taskPriority: "High",
    //     category: "Development",
    //     creationDate: "2026-01-06",
    //     active: true,
    //     new: true,
    //     completed: false,
    //     failed: false,
    //     assignedTo: "employee2@example.com",
    //   },
    //   {
    //     taskTitle: "Code Review",
    //     taskDescription: "Review PRs from teammates",
    //     taskPriority: "Low",
    //     category: "Development",
    //     creationDate: "2026-01-04",
    //     active: false,
    //     new: false,
    //     completed: true,
    //     failed: false,
    //     assignedTo: "employee2@example.com",
    //   },
    //   {
    //     taskTitle: "Optimize Queries",
    //     taskDescription: "Improve database query performance",
    //     taskPriority: "High",
    //     category: "Performance",
    //     creationDate: "2026-01-02",
    //     active: false,
    //     new: false,
    //     completed: false,
    //     failed: true,
    //     assignedTo: "employee2@example.com",
    //   },
    //   {
    //     taskTitle: "Design Landing Page",
    //     taskDescription: "Create UI design for new landing page",
    //     taskPriority: "High",
    //     category: "Design",
    //     creationDate: "2026-01-08",
    //     active: true,
    //     new: true,
    //     completed: false,
    //     failed: false,
    //     assignedTo: "employee3@example.com",
    //   },
    //   {
    //     taskTitle: "Update Brand Assets",
    //     taskDescription: "Refresh logo and color palette",
    //     taskPriority: "Low",
    //     category: "Design",
    //     creationDate: "2026-01-01",
    //     active: false,
    //     new: false,
    //     completed: true,
    //     failed: false,
    //     assignedTo: "employee3@example.com",
    //   },
    //   {
    //     taskTitle: "Prototype Review",
    //     taskDescription: "Review Figma prototype with team",
    //     taskPriority: "Low",
    //     category: "Review",
    //     creationDate: "2026-01-05",
    //     active: false,
    //     new: false,
    //     completed: false,
    //     failed: true,
    //     assignedTo: "employee3@example.com",
    //   },
    //   {
    //     taskTitle: "Write Test Cases",
    //     taskDescription: "Create unit test cases for auth module",
    //     taskPriority: "High",
    //     category: "Testing",
    //     creationDate: "2026-01-06",
    //     active: true,
    //     new: false,
    //     completed: false,
    //     failed: false,
    //     assignedTo: "employee4@example.com",
    //   },
    //   {
    //     taskTitle: "Regression Testing",
    //     taskDescription: "Run regression test suite",
    //     taskPriority: "Low",
    //     category: "Testing",
    //     creationDate: "2026-01-03",
    //     active: false,
    //     new: false,
    //     completed: true,
    //     failed: false,
    //     assignedTo: "employee4@example.com",
    //   },
    //   {
    //     taskTitle: "Bug Reporting",
    //     taskDescription: "Document and report found issues",
    //     taskPriority: "Low",
    //     category: "Documentation",
    //     creationDate: "2026-01-04",
    //     active: false,
    //     new: false,
    //     completed: false,
    //     failed: true,
    //     assignedTo: "employee4@example.com",
    //   },
    //   {
    //     taskTitle: "Server Monitoring",
    //     taskDescription: "Monitor server health and logs",
    //     taskPriority: "High",
    //     category: "DevOps",
    //     creationDate: "2026-01-07",
    //     active: true,
    //     new: true,
    //     completed: false,
    //     failed: false,
    //     assignedTo: "employee5@example.com",
    //   },
    //   {
    //     taskTitle: "Backup Setup",
    //     taskDescription: "Configure daily database backups",
    //     taskPriority: "High",
    //     category: "DevOps",
    //     creationDate: "2026-01-02",
    //     active: false,
    //     new: false,
    //     completed: true,
    //     failed: false,
    //     assignedTo: "employee5@example.com",
    //   },
    //   {
    //     taskTitle: "Deploy Patch",
    //     taskDescription: "Deploy security patch to production",
    //     taskPriority: "High",
    //     category: "Deployment",
    //     creationDate: "2026-01-01",
    //     active: false,
    //     new: false,
    //     completed: false,
    //     failed: true,
    //     assignedTo: "employee5@example.com",
    //   },
    // ],
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return {employees, admin};
};
